image: alpine

pages:
  script:
  - apk --no-cache add file git py3-pip python3-dev imagemagick zlib-dev jpeg-dev musl-dev py3-setuptools python3-dev gcc zip libxml2
  - convert --version
  - set LIBRARY_PATH=$LIBRARY_PATH:/lib:/usr/lib
  - pip3 install --upgrade pip
  - pip3 install Pillow
  - pip3 install sphinx sphinx-material sphinxcontrib.bibtex sphinx_git sphinxcontrib-actdiag sphinxcontrib-blockdiag sphinxcontrib-seqdiag sphinxcontrib-nwdiag
  - apk --no-cache add make
  - pwd
  - git checkout Entwicklung
  - git status
  - mkdir ~/.font
  - cp Quelltext/_static/source-sans-pro/TTF/* ~/.font
  - make html
  - mv Export/Entwicklung/html public
  artifacts:
    paths:
    - public
  only:
  - Entwicklung